### ISSUE TITLE
edit page header

### ISSUE THREAD

**Issue by abooks23** [bleutzinn/grav-plugin-editable-simplemde#11]
Hi
are there any plans to create plugin for edit page header from frontend?
edit tag and any custom fields?

**Comment by bleutzinn** [comment]
No, not that I am aware of.

The Add Page by Form plugin creates page header variables but it always creates a new page. It can not change page header data of an existing page.

Frontend or in context editing works best when editing is limited to content which is visible on the page. Editing meta data would require extra buttons which complicates the interface albeit slightly. It could be done with a slim menu bar on the top of the page though.

**Comment by abooks23** [comment]
ok, I understood you
