### ISSUE TITLE
No content displayed when plugin enabled

### ISSUE THREAD

**Issue by samurai-tools** [bleutzinn/grav-plugin-editable-simplemde#12]
Bleutzinn,
Fresh install of Grav with Admin (1.6.11), also tried with Antimatter theme.  

When plugin enabled, only the edit button shows up.
![blank page](https://user-images.githubusercontent.com/18474434/60912180-a82f0480-a239-11e9-9251-3ea0764d236d.png)
When I click it, it does show the page content for editing and allows me to save it.  But then we're back to a blank page.
![edit page](https://user-images.githubusercontent.com/18474434/60912181-a82f0480-a239-11e9-9d1c-7a3b78e0cd75.png)

### Errors
I do see a lot of these in the log files:
> July 9th at 10:45am | CRITICAL | Argument 1 passed to Grav\Common\Page\Markdown\Excerpts::__construct() must implement interface Grav\Common\Page\Interfaces\PageInterface or be null, instance of Grav\Plugin\EditableSimpleMDEPlugin given, called in /var/www/grav.test/system/src/Grav/Common/Markdown/Parsedown.php on line 32

### Environment
Ubuntu 19.04
Nginx 1.15.9
Chrome 75
Firefox 67

![plugins](https://user-images.githubusercontent.com/18474434/60912182-a82f0480-a239-11e9-8087-b59e2bc784f0.png)

![themes](https://user-images.githubusercontent.com/18474434/60912183-a82f0480-a239-11e9-8785-1066c9471dfe.png)

**Comment by bleutzinn** [comment]
Thanks for your detailed bug report.

Please test the new version 1.1.1 by downloading it from the repository. If all is working well I'll make a new release.

**Comment by samurai-tools** [comment]
Yes!  That did the trick! Tested it on Ubuntu and Windows, Chrome and Firefox!
Thank you for the quick response, it's much appreciated.

**Comment by bleutzinn** [comment]
You're welcome. Thanks for testing.
