### ISSUE TITLE
Add edit rights for the accounts that have admin privilege

### ISSUE THREAD

**Issue by tttp** [bleutzinn/grav-plugin-editable-simplemde#2]
Hi,
So it took me a while to understand why, as a super admin, I couldn't edit from the front end ;)
I have patched your awesome plugin to let the admin accounts edit from the frontend, as they do have it from the admin anyway, I thought it's the normal behaviour

Would you like me to PR?

**Comment by bleutzinn** [comment]
Thanks for your kudos and the time to prepare a fix. However I have doubts giving a user with admin permission automatically access to use the frontend editor.
As [the docs](https://learn.getgrav.org/admin-panel/faq#managing-acl) describe Grav separates backend and frontend user permissions and for that uses different sessions. Also not every user with admin rights is allowed to edit pages in the backend, only users with access levels `admin.super` and `admin.pages` have that right.
So I welcome a PR if you make a config option which allows admin users with access levels `admin.super` or `admin.pages` to edit pages in the frontend as well.
Perhaps like so in `editable-simplemde.yaml`:
```
editable-simplemde:
    by: admin.super
```
BTW the `editable-simplemde.by` is a kind of flashforward as I have been experimenting giving individual users and groups edit permissions. Your PR and my intention go very well together.

**Comment by DaleFranks** [comment]
This would be useful for me as well. I am the only user/author, as it's my personal web site. I'd like to be able to edit pages without creating a front end login page. It's would be very useful for making quick page edits without having to go into the back-end page editor in the Admin section.

**Comment by bleutzinn** [comment]
This is not on my roadmap at the moment. Of course anyone is invited to develop such a feature and do a pull request.
For now I'm closing this issue.

**Comment by bleutzinn** [comment]
Well it appears that with Grav version 1.1.6 (released in October 2016!) there's a configuration option to merge the backend and frontend sessions, see "Added option to control split session [#1096](https://github.com/getgrav/grav/pull/1096)". This option is set in `/user/config/system.yaml` or see the `System` tab of `Configuration` when using the Admin plugin.
