### ISSUE TITLE
Issue with tag of TOC plugin

### ISSUE THREAD

**Issue by roelfrenkema** [bleutzinn/grav-plugin-editable-simplemde#3]
There seems to be an issue with the [TOC] tag of https://github.com/Sommerregen/grav-plugin-toc When I put it in the page and save it everything is fine and I get a table. But next time I edit the page the tag is gone with any linefeeds surrounding it, garbling up my format.

**Comment by bleutzinn** [comment]
I can't replicate this. I installed the Toc Plugin without changing it's default settings.
When I insert [TOC] in the markdown from the frontend, then do a save and reload the page the table of contents appears on the right as expected.
Then again in edit mode, the [TOC] marker is still there and unchanged as is the rest of the markdown. Again saving, logging out and logging in, it all works fine for me.

This is the top part of my markdown test page:
```
## SimpleMDE demo !

[TOC]

This is **markdown**. You can edit me with SimpleMDE. 

![](_vlinder.jpg)
```

**Comment by roelfrenkema** [comment]
I know I doesn't happen all the time, but sometimes on editing the page. Can't point my finger on it but definitely after editing. I wonder if it is the TOC plugin itself that wants to replace the content of the [TOC] in the edit window but gets killed before it gets the chance to fill in a table.

**Comment by roelfrenkema** [comment]
OK I am going to close this as it seems not to happen anymore since I switched to another theme.
