### ISSUE TITLE
IE 11

### ISSUE THREAD

**Issue by roelfrenkema** [bleutzinn/grav-plugin-editable-simplemde#4]
Yes you read ir right IE 11 is the browser I have to use at work. Everything very strict there. One of the reasons I had to run a Grav site. But guess what? IE 11 seems to have a visibilty issue with the visibility option in the applet. As soon as I hit an editor enabled screen everything goes blank.  So it's no front Editor for me and back to the old admin account. BUMMER!!!!

**Comment by roelfrenkema** [comment]
OK I will tomorrow when I am at work, thanks for the effort I will report back ASAP

**Comment by bleutzinn** [comment]
Usually I don't have access to IE11 but managed to and did some testing. It appears IE11 has a problem with a script which runs fine in other browsers. I'll look into it.

**Comment by roelfrenkema** [comment]
Well to be exact it's the display:none css tag. Display is not fully supported by IE10 and up.

**Comment by bleutzinn** [comment]
That's what I thought too. However there was a problem with a parameter in the file upload code. I fixed that and it all seems to work fine even without the help of `!important`, so I reverted my previous change. Again the only modified file is `main.js`. (Beware of caching!)
Please let me know your findings.

**Comment by roelfrenkema** [comment]
Argghhh I wont be at work till monday but if it works for you I don't see why it wouldn't work for me. I will see if I can get a ie11 going on one of my many *nix boxes, maybe on Wine. I just hope it will not make me puke :-)

**Comment by roelfrenkema** [comment]
Ik gooi er wel even een VM tegenaan dan ben ik hem ook weer snel kwijt als hij klaar is.

**Comment by roelfrenkema** [comment]
Nope nada werkt niet. Nog steeds leeg scherm alleen in de source is de text te zien. Ik gebruik nu virtualbox met ie11 .

**Comment by roelfrenkema** [comment]
Voor de volledigheid zodat we elkaar kunnen controleren op het resultaat: https://github.com/magnetikonline/linuxmicrosoftievirtualmachines#ie11---windows-7

**Comment by bleutzinn** [comment]
To recap the status for everyone for whom the latest three posts are a mystery: the fix doesn't work with IE11 on a virtual machine. My test involved IE11 on a native Windows 7 professional install.
I'll try to setup the VM on MacOS and see what happens.

**Comment by bleutzinn** [comment]
I suggest we try to meet somewhere in real live and both look at the (mis)behaviour in your VM + IE setup. Can you send me an email? It's not hard to find but I prefer not to advertise it here as well.
