### ISSUE TITLE
enable systemwide

### ISSUE THREAD

**Issue by tatoosh** [bleutzinn/grav-plugin-editable-simplemde#5]
Thanks for the plugim that works for my setup only by enableing on every site.
Where to set it system wide?

```
editable-simplemde:
    self: true
```
Isn't it that file ?
` user/config/plugins/editable-simplemde.yaml `

**Comment by bleutzinn** [comment]
Make sure your `user/config/plugins/editable-simplemde.yaml` looks like:
```
enabled: true
self: true
```
BTW the line `editable-simplemde:` isn't needed.

To disable certain pages to be editable put this in the page frontmatter:
```
editable-simplemde:
    self: false
```

**Comment by bleutzinn** [comment]
Improved the [documentation](https://github.com/bleutzinn/grav-plugin-editable-simplemde/blob/master/README.md) on this matter. Thanks for pointing me to it.
