### ISSUE TITLE
Working with Private Grav Plugin

### ISSUE THREAD

**Issue by Kokozzi** [bleutzinn/grav-plugin-editable-simplemde#6]
Hi,
Can you provide an example of working with Private Plugin? If I'm right, this plugin doesn't work with user account files, and it's not obvious where to add ` editable: 'true'` statement

**Comment by bleutzinn** [comment]
I have no experience using the Private Plugin. You could ask fellow Grav users on the [forum](https://discourse.getgrav.org).
