### ISSUE TITLE
Not showing Content

### ISSUE THREAD

**Issue by NHISystems** [bleutzinn/grav-plugin-editable-simplemde#8]
Dear Bleutzinn,

i installed the Addon.
Now the edit button is showing up but not working and all my content pages are empty.

Thanks for Help
NHI

**Comment by bleutzinn** [comment]
When the Edit button is not working the problem often is with the theme. Can you please try with the standard Antimatter theme?

**Comment by NHISystems** [comment]
Okay i use Learn2 Template right know. I want to build a Dokumentation with Front End editing for my Members. Is there a way to get it working on Learn2 Template?

**Comment by bleutzinn** [comment]
Your best option is to use your browser developer tools and examine what other elements are overlaying the button(s). Maybe you can look into setting the CSS z-index property of the Edit/, Save and Close buttons to a high value so the buttons are on top.

**Comment by bleutzinn** [comment]
I assume you have found a solution. If not please re-open this issue.
